//
//  GrocerySections.swift
//  Naramsetty_GroceryApp
//
//  Created by student on 4/12/22.
//

import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Food",items_Array:[GroceryItem(itemName:"HydsplBiryani",itemImage:"Biryani",itemInfo:"AHyderabadi biryani, also known as Hyderabadi dum biryani, is a style of biryani from Hyderabad, India made with basmati rice and meat (mostly chicken, Lamb Meat). Originating in the kitchens of the Nizam of Hyderabad, it combines elements of Hyderabadi and Mughlai cuisines. Hyderabad biryani is a key dish in Hyderabadi cuisine"), GroceryItem(itemName: "kichidi", itemImage: "khichdi", itemInfo: "Khichdi or Khichri is a dish in South Asian cuisine made of rice and lentils, but other variations include bajra and mung dal khichri. In Indian culture, in several regions, especially in the northern areas, it is considered one of the first solid foods that babies eat."), GroceryItem(itemName: "Hot Pongal", itemImage: "pongal", itemInfo: "Pongal is a delicious South Indian porridge made with rice and yellow moong lentils. It can be made sweet or savory. Here I share the savory version of pongal recipe known as Ven Pongal or Khara Pongal laced with the wonderful flavors of cumin, asafetida, curry leaves, ginger and black pepper. Not to forget the lovely aroma of ghee, in it"), GroceryItem(itemName: "idly", itemImage: "idly", itemInfo: "Idli or idly are a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented black lentils and rice."), GroceryItem(itemName: "dosa", itemImage: "dosa", itemInfo: "A dosa is a thin flat bread originating from South India, made from a fermented batter predominantly consisting of lentils and rice. Its main ingredients are rice and black gram, ground together in a fine, smooth batter with a dash of salt, then fermented.")] )

let groceryitem2 = Grocery( section: "Meat", items_Array: [GroceryItem(itemName: "chicken", itemImage: "chicken", itemInfo: "Chicken is the most common type of poultry in the world. Owing to the relative ease and low cost of raising chickens—in comparison to mammals such as cattle or hogs—chicken meat and chicken eggs have become prevalent in numerous cuisines."), GroceryItem(itemName: "Mutton", itemImage: "mutton", itemInfo: "Lamb, hogget, and mutton, generically sheep meat, are the meat of domestic sheep, Ovis aries. A sheep in its first year is a lamb and its meat is also lamb. The meat from sheep in their second year is hogget. Older sheep meat is mutton. "), GroceryItem(itemName: "Fish", itemImage: "fish", itemInfo: "IMany species of fish are caught by humans and consumed as food in virtually all regions around the world. Fish has been an important dietary source of protein and other nutrients throughout human history."), GroceryItem(itemName: "crabs™", itemImage: "crabs", itemInfo: "Crab meat or crabmeat is the meat found within a crab. It is used in many cuisines around the world, prized for its soft, delicate and sweet taste. Crab meat is low in fat and provides around 340 kilojoules of food energy per 85-gram serving"), GroceryItem(itemName: "deer", itemImage: "deer", itemInfo: "Venison originally meant the meat of a game animal but now refers primarily to the meat of antlered ungulates such as elk or deer. Venison can be used to refer to any part of the animal, so long as it is edible, including the internal organs")] )

let groceryitem3 = Grocery( section: "Novels", items_Array: [GroceryItem(itemName: "A Tale of Two Cities", itemImage: "book1", itemInfo: "A Tale of Two Cities is an 1859 historical novel by Charles Dickens, set in London and Paris before and during the French Revolution. The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris, and his release to live in London with his daughter Lucie whom he had never met. "), GroceryItem(itemName: "The Little Prince", itemImage: "book2", itemInfo: "The Little Prince (French: Le Petit Prince, pronounced [lə p(ə)ti pʁɛ̃s]) is a novella by French aristocrat, writer, and military aviator Antoine de Saint-Exupéry. It was first published in English and French in the United States by Reynal & Hitchcock in April 1943. "), GroceryItem(itemName: "Harry Potter and the Philosopher's Stone", itemImage: "book3", itemInfo: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry."), GroceryItem(itemName: "And Then There Were None", itemImage: "book4", itemInfo: "And Then There Were None is a mystery novel by the English writer Agatha Christie, described by her as the most difficult of her books to write.[2] It was first published in the United Kingdom by the Collins Crime Club on 6 November 1939, as Ten Little Niggers."), GroceryItem(itemName: "Dream of the Red Chamber", itemImage: "book5", itemInfo: "Dream of the Red Chamber (Honglou Meng) or The Story of the Stone (Shitou Ji) is a novel composed by Cao Xueqin in the middle of the 18th century. One of the Four Great Classical Novels of Chinese literature, it is known for its psychological scope, and its observation of the world view, aesthetics, life-styles, and social relations of 18th-century China.")] )

let groceryitem4 = Grocery( section: "Fruits", items_Array: [GroceryItem(itemName: "Apple", itemImage: "apple", itemInfo: "An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today"), GroceryItem(itemName: "orange", itemImage: "orange", itemInfo: "An orange is a fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange."), GroceryItem(itemName: "banana", itemImage: "banana", itemInfo: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called plantains distinguishing them from dessert bananas"), GroceryItem(itemName: "Blackberry", itemImage: "blackberry", itemInfo: "The blackberry is an edible fruit produced by many species in the genus Rubus in the family Rosaceae, hybrids among these species within the subgenus Rubus, and hybrids between the subgenera Rubus and Idaeobatus"), GroceryItem(itemName: "guava", itemImage: "guava", itemInfo: "Guava is a common tropical fruit cultivated in many tropical and subtropical regions. The common guava Psidium guajava is a small tree in the myrtle family, native to Mexico, Central America, the Caribbean and northern South America.")] )

let groceryitem5 = Grocery( section: "Pulses", items_Array: [GroceryItem(itemName: "Blackgram", itemImage: "blackgram", itemInfo: "Vigna mungo, the black gram, urad bean, mash kalai, uzhunnu parippu, ulundu paruppu, minapa pappu, Uddu or black matpe is a bean grown in South Asia. Like its relative, the mung bean, it has been reclassified from the Phaseolus to the Vigna genus."), GroceryItem(itemName: "Greengram", itemImage: "greengram", itemInfo: "The mung bean, alternatively known as the green gram, maash, moong, monggo, or munggo, is a plant species in the legume family. The mung bean is mainly cultivated in East, Southeast and South Asia. It is used as an ingredient in both savoury and sweet dishes."), GroceryItem(itemName: "kidneybeans", itemImage: "kidneybeans", itemInfo: "The kidney bean is a variety of the common bean. It resembles a human kidney and thus is named after such. Red kidney beans should not be confused with other red beans, such as adzuki beans or pinto beans."), GroceryItem(itemName: "Bengal gram", itemImage: "bengalgram", itemInfo: "The chickpea or chick pea is an annual legume of the family Fabaceae, subfamily Faboideae. Its different types are variously known as gram or Bengal gram, garbanzo or garbanzo bean, or Egyptian pea. Chickpea seeds are high in protein."), GroceryItem(itemName: "toordal", itemImage: "toordal", itemInfo: "AA yellow coloured lentil flat on one side, oblong in shape, used widely in Indian cooking. Pigeon pea is commonly known as arhar dal or split toor (tuvar) dal. It has its origins in the Eastern part of peninsular India. It is both a food crop and a cover crop. ")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]
